services:
  web:
    build: .
    container_name: tib_armory_app
    restart: always
    # ports:
    #   - "8003:8000" # Exposed via Traefik now
    volumes:
      - ./data:/app/data
      - ./static/uploads:/app/static/uploads
      - ./templates:/app/templates
    env_file:
      - .env
    environment:
      - DATABASE_URL=sqlite:///data/tib_armory.db
    networks:
      - tib_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.armory.rule=Host(`armory.tib-usa.app`)"
      - "traefik.http.routers.armory.entrypoints=websecure"
      - "traefik.http.routers.armory.tls.certresolver=myresolver"
      - "traefik.http.services.armory.loadbalancer.server.port=8000"

networks:
  tib_network:
    external: true
